/**
 用户表
*/
CREATE TABLE U_USER(
  USER_ID VARCHAR(36) NOT NULL PRIMARY KEY COMMENT '主键',
  USER_NAME VARCHAR(36) COMMENT '姓名',
  USER_IDCARD VARCHAR(36) COMMENT '身份证号',
  USER_BIRTHDATE DATE  COMMENT '出生日期',
  USER_BIRTHADREE VARCHAR(255) COMMENT '出生地',
  USER_PHONE VARCHAR(36) COMMENT '电话号码',
  USER_CODE VARCHAR(36)  COMMENT '用户编号',
  USER_PASSWORD VARCHAR (255) COMMENT '用户密码',
  USER_EMAIL VARCHAR (255) COMMENT '用户邮箱',
  USER_IMAGE LONGBLOB COMMENT '用户头像'
)